[package]
name = "pku3b"
version = "0.1.0"
edition = "2024"

[dependencies]
cyper = { git = "https://github.com/compio-rs/cyper.git", rev = "c4b569d408b540b2d8d84c1b68396bfe6fb18798", features = [
    "cookies",
] }
compio = { version = "0.13", features = ["macros"] }
anyhow = "1.0"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9.0"
http = "1.2.0"
scraper = "0.23.1"
directories = "6.0.0"
regex = "1.11.1"
clap = { version = "4.5.31", features = ["derive"] }
rpassword = "7.3.1"
