[package]
name = "pku3b"
version = "0.1.0"
edition = "2024"
authors = ["Weiyao Huang <jy.cat@qq.com>"]
license = "MIT"
description = "A tool for PKU students to check their courses."
readme = "README.md"
homepage = "https://github.com/sshwy/pku3b"
repository = "https://github.com/sshwy/pku3b"
keywords = ["cli"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = { version = "1.0", default-features = false }
chrono = { version = "0.4.40", default-features = false, features = ["clock"] }
clap = { version = "4.5.31", features = ["derive"] }
compio = { version = "0.13", features = ["macros"], default-features = false }
cyper = { git = "https://github.com/compio-rs/cyper.git", rev = "c4b569d408b540b2d8d84c1b68396bfe6fb18798", default-features = false, features = [
    "cookies",
    "native-tls",
] }
directories = "6.0.0"
http = { version = "1.2.0", default-features = false }
rand = { version = "0.9.0", features = [
    "thread_rng",
], default-features = false }
regex = "1.11.1"
rpassword = "7.3.1"
scraper = { version = "0.23.1", default-features = false }
serde = { version = "1.0", features = [
    "serde_derive",
], default-features = false }
serde_json = "1.0"
toml = "0.8"
