[package]
name = "pku3b"
version = "0.1.0"
edition = "2024"

[dependencies]
cyper = { git = "https://github.com/compio-rs/cyper.git", rev = "c4b569d408b540b2d8d84c1b68396bfe6fb18798", default-features = false, features = [
    "cookies",
    "native-tls",
] }
compio = { version = "0.13", features = ["macros"], default-features = false }
anyhow = { version = "1.0", default-features = false }
toml = "0.8"
serde = { version = "1.0", features = [
    "serde_derive",
], default-features = false }
serde_json = "1.0"
rand = { version = "0.9.0", features = [
    "thread_rng",
], default-features = false }
http = { version = "1.2.0", default-features = false }
scraper = { version = "0.23.1", default-features = false }
directories = "6.0.0"
regex = "1.11.1"
clap = { version = "4.5.31", features = ["derive"] }
rpassword = "7.3.1"
